#!/bin/sh -e

./gradlew -q --console plain installDist

JAVA_OPTS=-Xbootclasspath/p:$HOME/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.9.v20160720/alpn-boot-8.1.9.v20160720.jar \
./build/install/rsocket-cli/bin/rsocket-cli "$@"
